namespace NDivert.Filter
{
	/// <summary>
	/// WINDIVERT_FILTER_FIELD_*
	/// </summary>
	public enum FilterField
		: byte
	{
		Zero = 0,
		Inbound = 1,
		Outbound = 2,
		IfIdx = 3,
		SubIfIdx = 4,
		Ip = 5,
		Ipv6 = 6,
		Icmp = 7,
		Tcp = 8,
		Udp = 9,
		Icmpv6 = 10,
		IpHeaderLength = 11,
		IpTos = 12,
		IpLength = 13,
		IpId = 14,
		IpDf = 15,
		IpMf = 16,
		IpFragOff = 17,
		IpTtl = 18,
		IpProtocol = 19,
		IpChecksum = 20,
		IpSourceAddress = 21,
		IpDestinationAddress = 22,
		Ipv6TrafficClass = 23,
		Ipv6FlowLabel = 24,
		Ipv6Length = 25,
		Ipv6NextHeader = 26,
		Ipv6HopLimit = 27,
		Ipv6SourceAddress = 28,
		Ipv6DestinationAddress = 29,
		IcmpType = 30,
		IcmpCode = 31,
		IcmpChecksum = 32,
		IcmpBody = 33,
		Icmpv6Type = 34,
		Icmpv6Code = 35,
		Icmpv6Checksum = 36,
		Icmpv6Body = 37,
		TcpSourcePort = 38,
		TcpDestinationPort = 39,
		TcpSequenceNumber = 40,
		TcpAckNumber = 41,
		TcpHeaderLength = 42,
		TcpUrgent = 43,
		TcpAck = 44,
		TcpPsh = 45,
		TcpRst = 46,
		TcpSyn = 47,
		TcpFin = 48,
		TcpWindow = 49,
		TcpChecksum = 50,
		TcpUrgPtr = 51,
		TcpPayloadLength = 52,
		UdpSourcePort = 53,
		UdpDestinationPort = 54,
		UdpLength = 55,
		UdpChecksum = 56,
		UdpPayloadLength = 57
	}
}
